### ISSUE TITLE
remove strings

### ISSUE THREAD

**Issue by AlassePrince** [Spatchy/Infinite-Craft-Plus-Plus#33]
i always seem to make things in way to many ways example 

avatar 

airbender + katara = avatar 
anng + earthbender = avatar 

this goes on and on while i had already long discovered avatar

i would like it if the lines between items got removed if you already discovered the item that the combination of those 2 things would make

**Comment by Spatchy** [comment]
This is certainly an interesting idea, but my gut instinct is that it's impossible given the restrictions placed on browser extensions. This feature might be more suited to a userscript-based mod like InfiniteCraftHelper
